name: run-py-script

on: 
  push:
    branches: [master, release/*]

jobs:
  set_up:
    name: Set up
    runs-on: ubuntu-latest
    
    steps:
      - name: print a env var
        run: |
          echo "${GITHUB_REF}"
          echo "${{github.ref}}"
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Trigger infrastructure repo workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Update-infrastructure-backend
          ref: master
          inputs: '{"sha-tag" : "${{ github.sha }}/imgonnalive:forever${{steps.extract_branch.outputs.branch}}", "code-branch" : "${{steps.extract_branch.outputs.branch}}"}'
          repo: mattedamo/thesis-infr-repo-python
          token: ${{ secrets.API_TOKEN_GITHUB }}
